version: "3.8"

services:
  # Backend service
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=5050
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_ACCESS_TOKEN=${GOOGLE_ACCESS_TOKEN}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - GOOGLE_TOKEN_EXPIRY=${GOOGLE_TOKEN_EXPIRY}
      - GOOGLE_PHOTOS_ALBUM_ID=${GOOGLE_PHOTOS_ALBUM_ID}
    volumes:
      - ./tokens:/data/tokens
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ../habits-ui
    container_name: frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

# Network for all services
networks:
  app-network:
    driver: bridge
