version: "3.8"

services:
  # Backend service
  backend:
    build:
      context: .
      args:
        - NODE_ENV=staging
    container_name: backend-staging
    restart: unless-stopped
    ports:
      - "5051:5050"
    environment:
      - NODE_ENV=staging
      - PORT=5050
      - MONGODB_URI=${MONGODB_URI_STAGING:-${MONGODB_URI}}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI_STAGING:-${GOOGLE_REDIRECT_URI}}
      - GOOGLE_ACCESS_TOKEN=${GOOGLE_ACCESS_TOKEN}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - GOOGLE_TOKEN_EXPIRY=${GOOGLE_TOKEN_EXPIRY}
      - GOOGLE_PHOTOS_ALBUM_ID=${GOOGLE_PHOTOS_ALBUM_ID}
    networks:
      - staging-network

  # Frontend service
  frontend:
    build:
      context: ../habits-ui
      args:
        - VITE_API_URL=/api
        - VITE_BACKEND_URL=http://backend-staging:5050
    container_name: frontend-staging
    restart: unless-stopped
    ports:
      - "5174:80"
    environment:
      - BACKEND_URL=http://backend-staging:5050
    depends_on:
      - backend
    networks:
      - staging-network

# Network for all services
networks:
  staging-network:
    driver: bridge
