version: "3.8"

services:
  # Backend service
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=5050
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ../FE
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

# Network for all services
networks:
  app-network:
    driver: bridge
