name: API Build and Deploy

on:
  push:
    branches:
      - main # Production build
      - staging # Staging build
  workflow_dispatch:

jobs:
  build-deploy:
    uses: ./.github/workflows/reusable.yml
    with:
      run-tests: true
      run-build: true
      run-docker: true
      environment-tag: ${{ github.ref == 'refs/heads/main' && 'latest' || 'staging' }}
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
