name: API CI

on:
  push:
    branches-ignore: [main] # Run on all branches except main
  pull_request:
    branches: [main] # Run on PRs targeting main

jobs:
  ci-process:
    uses: ./.github/workflows/reusable.yml
    with:
      run-tests: true
      run-build: true
      run-docker: false
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_VALID_TOKEN: ${{ secrets.TEST_VALID_TOKEN }}
      TEST_INVALID_TOKEN: ${{ secrets.TEST_INVALID_TOKEN }}
